In [1]:
# libraries
import numpy as np

In [36]:

# array concat and split

# concat is done by concatenate, hstack, vstack

ar_1 = np.array([1,1,1])
ar_2 = np.array([2,2,2])
ar_3 = np.array([3,3,3])


ar_12 = np.concatenate([ar_1, ar_2])
ar_12

array([1, 1, 1, 2, 2, 2])

In [5]:
ar_12h = np.hstack([ar_1, ar_2])
ar_12h

array([1, 1, 1, 2, 2, 2])

In [6]:

ar_12v = np.vstack([ar_1, ar_2])
ar_12v

array([[1, 1, 1],
       [2, 2, 2]])

In [7]:
ar_123 = np.vstack([ar_1, ar_2, ar_3])
ar_123

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [23]:
# the opposite of concat is split
# split is done by split, hsplit, vsplit

ar_1s, ar_2s = np.split(ar_12, [4])

print(ar_1s, ar_2s)

[1 1 1 2] [2 2]


In [28]:
# split multidim arrays

# add another dim to ar_123
ar_4 = np.array([4,4,4])
ar_1234 = np.vstack([ar_123, ar_4])

ar_1234

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [35]:
# split ar_1234
ar_12, ar_34 = np.vsplit(ar_1234, [2])
ar_12

array([[1, 1, 1],
       [2, 2, 2]])

In [34]:
ar_34

array([[3, 3, 3],
       [4, 4, 4]])