In [1]:
import numpy as np

In [3]:
test_ar = np.array([1,2,3,4,5])
test_ar

array([1, 2, 3, 4, 5])

In [4]:
test_ar < 3

array([ True,  True, False, False, False])

In [6]:
np.sum(test_ar < 3)

2

In [8]:
np.sum(test_ar == 3)

1

You can combine this with axis= to count per row/col

.any() and .all()

In [9]:
np.any(test_ar == 0)

False

In [10]:
np.any(test_ar == 3)

True

In [11]:
np.all(test_ar > 0)

True

You can also use boooleans

In [13]:
np.sum((test_ar <= 2) | (test_ar > 3))

4

In [14]:
np.sum((test_ar != 3) & (test_ar != 4))

3

using booleans to select elements

In [15]:
test_ar[test_ar <= 4]

array([1, 2, 3, 4])

Don't forget the and / or / in operators