Library

In [8]:
import numpy as np

In [5]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [11]:
x = np.arange(9).reshape(3,3)
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [16]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [17]:
x + 5

array([[5, 6],
       [7, 8]])

In [19]:
abs(x-100)

array([[100,  99],
       [ 98,  97]])

In [22]:
x = np.add.reduce(x)
x

6

vectorized code rules, just like R