In [2]:
import numpy as np

Aggregates: Min, Max, and everything in between

In [10]:
l = np.random.random(size=100)*100
l

array([48.57282784, 89.76196995, 39.70297871, 96.0582976 , 78.35445257,
       27.66437755, 98.60982797, 10.8152336 , 80.25796138, 16.83155177,
       83.61047515,  9.17543044, 79.67868002, 48.08467797, 85.3116088 ,
       88.47089893, 52.92064507, 11.20332628, 55.64502081, 14.63568799,
       25.29178746, 73.34950692,  4.8328687 , 57.33048858,  3.26169931,
       84.18384908, 14.58825457, 67.05821055, 92.03149495, 52.10491764,
        9.00691478, 53.28072628, 40.36013502, 23.00566313, 72.6533661 ,
       28.01270121, 49.49629233, 73.5582397 , 32.42792731, 40.28186652,
       86.42361463, 92.67428849, 96.24739286, 61.61975332, 52.45970443,
       71.06703644,  1.8318376 , 13.04361875, 39.02125465, 36.50501341,
       64.30248398, 85.10532646, 14.91566377, 56.08413482, 17.38266037,
       23.51765223, 80.9022949 , 84.30441252, 55.87714629, 29.30439434,
       31.22713783, 58.31614237, 29.96103328, 78.8086551 , 33.4210203 ,
       16.60492036, 82.87133188, 10.86361965,  5.52584015, 49.95

In [12]:
np.mean(l)

50.5858336130178

In [13]:
np.median(l)

52.629024408856964

In [16]:
np.mode(l)

AttributeError: module 'numpy' has no attribute 'mode'

Mode doesn't exist in numpy!

In [17]:
from scipy import stats # import from SciPy

In [18]:
stats.mode(l)

ModeResult(mode=array([1.65339622]), count=array([1]))

Result doesn't make a ton of sense because no number is the 'most common'

In [19]:
np.sum(l)

5058.583361301779

In [21]:
np.min(l)

1.6533962183954531

In [22]:
np.max(l)

98.60982796563266

Use numpy over base for min/max because of speed

In [26]:
multi_array = np.random.random((3,4))*100
multi_array

array([[ 9.97876041, 94.38642608, 57.5288812 , 19.37849893],
       [46.98013826, 85.90614935, 98.26251531, 65.80457246],
       [79.59656258, 94.07316269, 70.99759261, 48.91246327]])

Performing operations on a subset of the data

In [27]:
multi_array.sum(axis=0) # sum along columns

array([136.55546125, 274.36573812, 226.78898912, 134.09553466])

In [28]:
multi_array.sum(axis=1) # sum along rows

array([181.27256661, 296.95337538, 293.57978116])